
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'src/Financeiro.sln'
  buildConfiguration: 'Release'
  CONNECTION_STRING: 'Server=localhost;Port=3303;Database=Financeiro;Uid=root;Pwd=Secret@1234;'

steps:
- task: DotNetCoreCLI@2
  displayName: .Net Core Restore
  inputs:
    command: restore
    projects: 'src/**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: .Net Core Build
  inputs:
    command: build
    projects: 'src/**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: .Net Core Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/**/*.csproj'
    arguments: --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: Artifacts Publish
